// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package main

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Error struct {
		// Human-readable error description
		Message string `json:"message"`
	} `json:"error"`
}

// ListTargetsResponse defines model for ListTargetsResponse.
type ListTargetsResponse = []struct {
	Name string `json:"name"`
}

// RegisterDeviceRequest defines model for RegisterDeviceRequest.
type RegisterDeviceRequest struct {
	// hardware id of the device which wishes to connect
	HardwareId *string `json:"hardwareId,omitempty"`
}

// RegisterDeviceResponse defines model for RegisterDeviceResponse.
type RegisterDeviceResponse struct {
	// device id which has been assigned to the device
	DeviceId *string `json:"deviceId,omitempty"`

	// device token which is signed and authenticates the device
	DeviceToken *string `json:"deviceToken,omitempty"`
}

// UpdateTarget defines model for UpdateTarget.
type UpdateTarget struct {
	// action to complete for user (modify / delete)
	Action *string `json:"action,omitempty"`

	// email of the user to modify
	UserEmail *string `json:"userEmail,omitempty"`

	// type of user (admin / user), if modifying
	UserType *string `json:"userType,omitempty"`
}

// Target defines model for target.
type Target = string

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetAuthLoginParams defines parameters for GetAuthLogin.
type GetAuthLoginParams struct {
	// code response from Google OAuth
	Code string `form:"code" json:"code"`
}

// PatchTargetTargetJSONBody defines parameters for PatchTargetTarget.
type PatchTargetTargetJSONBody = UpdateTarget

// PostTargetTargetRegisterDeviceJSONBody defines parameters for PostTargetTargetRegisterDevice.
type PostTargetTargetRegisterDeviceJSONBody = RegisterDeviceRequest

// PatchTargetTargetJSONRequestBody defines body for PatchTargetTarget for application/json ContentType.
type PatchTargetTargetJSONRequestBody = PatchTargetTargetJSONBody

// PostTargetTargetRegisterDeviceJSONRequestBody defines body for PostTargetTargetRegisterDevice for application/json ContentType.
type PostTargetTargetRegisterDeviceJSONRequestBody = PostTargetTargetRegisterDeviceJSONBody
