// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetControlPlaneAuth() {
  return window['go']['main']['App']['GetControlPlaneAuth']();
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
