// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {main} from '../models';

export function Connect(arg1:string,arg2:common.ClientOptions):Promise<main.WrappedReturn>;

export function Disconnect():Promise<main.WrappedReturn>;

export function GetControlPlaneAuth():Promise<main.WrappedReturn>;

export function List():Promise<Array<string>>;

export function Login(arg1:string):Promise<main.WrappedReturn>;

export function Status():Promise<main.WrappedReturn>;

export function Version():Promise<string>;
