packageExtensions:
  # These are patches to packages which do not declare their dependencies
  # correctly

  'react-hot-toast@*':
    peerDependencies:
      csstype: '^3.0.10'

  '@vitejs/plugin-react@2.2.0':
    dependencies:
      # Copied from vitejs/vite-plugin-react:package.json (root devDeps)
      '@types/babel__core': '^7.1.20'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
