openapi: "3.0.2"
info:
  title: rVPN Control Plane API
  version: "1.0"
servers:
  - url: https://{instance}/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  parameters:
    target:
      name: target
      in: path
      required: true
      schema:
        type: string
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              description: Human-readable error description
          required:
            - message
      required:
        - error
    ListTargetsResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
        required:
          - name
    UpdateTarget:
      type: object
      properties:
        userEmail:
          type: string
          description: email of the user to modify
        action:
          type: string
          description: action to complete for user (modify / delete)
        userType:
          type: string
          description: type of user (admin / user), if modifying
    RegisterDeviceRequest:
      type: object
      properties:
        hardwareId:
          type: string
          description: hardware id of the device which wishes to connect
    RegisterDeviceResponse:
      type: object
      properties:
        deviceId:
          type: string
          description: device id which has been assigned to the device
        deviceToken:
          type: string
          description: device token which is signed and authenticates the device
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

paths:
  /target/:
    get:
      summary: Returns available connection targets
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTargetsResponse"
  /target/{target}:
    put:
      summary: Create a target
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/target"
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/Unauthorized"
    patch:
      summary: Update a target
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/target"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTarget"
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/Unauthorized"
  /target/{target}/register_device:
    post:
      summary: Register a device on a target
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/target"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDeviceRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterDeviceResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
  /target/{target}/serve:
    get:
      summary: WebSocket to start serving VPN traffic from a server
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/target"
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/Unauthorized"
  /target/{target}/connect:
    get:
      summary: WebSocket to create a new device connection on a target
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/target"
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/Unauthorized"
  /auth/login:
    get:
      summary: OAuth redirect handler
      description: |-
        User login page - send the user here in a browser to get an auth token and complete the OAuth flow;
        this is *not* an API route.
      parameters:
        - name: code
          in: query
          required: true
          description: code response from Google OAuth
          schema:
            type: string
      responses:
        "302":
          description: Login page
