# vim: ft=yaml ts=2 et

name: CI
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:

jobs:
  client-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version

      - name: Install Gox
        run: go install github.com/mitchellh/gox@latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node --version

      - name: Install NSIS
        run: sudo apt-get install -y nsis
      - run: makensis -VERSION

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: wails doctor

      - name: Compile CLI clients
        run: |
          gox -osarch='linux/amd64 windows/amd64 darwin/arm64 darwin/amd64' \
            -output='build/{{.Dir}}_{{.OS}}_{{.Arch}}' \
            ./cmd/client

      - name: Compile Windows GUI client
        run: scripts/build-windows.sh

      - name: Move files around for final artifact upload
        run: |
          mv cmd/client_gui/build/bin/rvpn-amd64-installer.exe build/
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/

  release:
    runs-on: ubuntu-22.04
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
      - client-build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: binaries
          path: build/

      - name: Build archives for release
        run: |
          for arch in amd64; do
            mkdir -p build/package/rvpn_linux_$arch/{,bin/,systemd/}
            cp build/client_linux_$arch build/package/rvpn_linux_$arch/bin/rvpn
            cp -r support/systemd/ build/package/rvpn_linux_$arch/
            tar --owner root --group root --sort name \
              -C build/package/ -czvf rvpn_linux_$arch.tar.gz rvpn_linux_$arch
          done
          for arch in amd64 arm64; do
            mkdir -p build/package/rvpn_darwin_$arch/{,bin/,systemd/}
            cp build/client_darwin_$arch build/package/rvpn_darwin_$arch/bin/rvpn
            cp -r support/launchd/ build/package/rvpn_darwin_$arch/
            tar --owner root --group root --sort name \
              -C build/package/ -czvf rvpn_darwin_$arch.tar.gz rvpn_darwin_$arch

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            rvpn_linux_*.tar.gz
            build/rvpn-amd64-installer.exe
